### PR TITLE
Fix/6051 Facility Location filtering not working in Error Suppression Module

### LINKED ISSUE #6051: Facility Location filtering not working in Error Suppression Module
The Facility Name/ ID and Location Name fields do not filter correctly when searching for error suppressions. Entering a Facility Name/ ID and clicking Apply Filters does nothing, and the Location Name dropdown does not work.

## Acceptance Tests:
1. Enter a Facility Name or ID in the "Facility Name/ ID" field and click "Apply Filters".
The appropriate facility is returned.
2. The "Location Name" dropdown allows the selection of a specific Location Name. After selection, the appropriate location is returned.

### PR DESCRIPTION
**Pull request by Jhernandez29**
Ticket
https://github.com/US-EPA-CAMD/easey-ui/issues/6051

Changes

Updated \src\error-suppressions\error-suppressions.repository.getErrorSuppressions method with location instead of locations.join() because the pass param is a string.

### CODE REVIEW

File: src/error-suppressions/error-suppressions.repository.ts [hunk 1]
```diff
@@ -83,7 +83,7 @@ export class ErrorSuppressionsRepository extends Repository<EsSpec> {
     if (locations) {
       query.andWhere(
         `string_to_array(es.locations, ',') && string_to_array(:locations, ',')`,
-        { locations: locations.join(',') },
+        { locations: locations },
```
Comment (maxdiebold-erg) [inline src/error-suppressions/error-suppressions.repository.ts]: The `string_to_array` function splits a string into an array. Since the `locations` request parameter is an array, the original code correctly used `join(',')` to stringify it. Alternatively, the array could be passed in directly, e.g.:
```typescript
      query.andWhere(
        `string_to_array(es.locations, ',') && :locations`,
        { locations },
      );
```

**Review by maxdiebold-erg — CHANGES_REQUESTED** [review]
This doesn't seem to be working as expected. I think the initial implementation was correct, and it works when I test it, but I did leave a suggestion for a slightly more concise way below.

On a different note, I think if we intend to allow filtering by facility & location _without_ including check* filters, then `@IsOptional()` should be added to those fields in the **`ErrorSuppressionsParamsDTO`**.

**Comment by Jhernandez29** [comment]
ErrorSuppressionsParamsDTO

  @ApiProperty()
  @IsNumber()
  @IsOptional()
  @Type(() => Number)
  orisCode?: number;

  @IsOptional()
  @ApiProperty({ isArray: true })
  @Transform(({ value }) => value.split('|').map((item) => item.trim()))
  @IsArray()
  locations?: string[];
 
They do have the @IsOptional()

**Comment by maxdiebold-erg** [comment]
@Jhernandez29 I should have been more specific, I mean that `checkTypeCode`, `checkNumber`, and `checkResult` will need the `@IsOptional()` decorator.

File: src/error-suppressions/error-suppressions.repository.ts [hunk 2]
```diff
@@ -83,7 +83,7 @@ export class ErrorSuppressionsRepository extends Repository<EsSpec> {
     if (locations) {
       query.andWhere(
         `string_to_array(es.locations, ',') && string_to_array(:locations, ',')`,
```
Comment (maxdiebold-erg) [inline src/error-suppressions/error-suppressions.repository.ts]: When passing in an array, this should be updated:
```suggestion
        `string_to_array(es.locations, ',') && :locations`,
```

Comment (Jhernandez29) [reply src/error-suppressions/error-suppressions.repository.ts]: committed change requested

**Comment by maxdiebold-erg** [comment]
Looks good, thanks for making that change!

**Review by maxdiebold-erg — APPROVED** [review]
